name: boonjae
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.4.1+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  async_preferences: ^0.8.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.3
  cloud_functions: ^4.6.5
  firebase_analytics: ^10.8.7
  firebase_app_check: ^0.2.1+14
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.16
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_image_compress: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  iabtcf_consent_info: ^3.1.0
  image: ^4.1.7
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  provider: ^6.1.1
  rive: ^0.12.4
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  user_messaging_platform: ^1.3.0
  uuid: ^4.3.3
  web_browser: ^0.7.4
  weekday_selector: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/icon5.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/rive/
