name: boonjae
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.3
  cloud_functions: ^4.6.5
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_localizations:
    sdk: flutter
  image: ^4.1.7
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.1.1
  sqflite: ^2.3.2
  uuid: ^4.3.3
  weekday_selector: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
