// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1AfiypZ_Q9coX664MVES1i1olLp5V8t0',
    appId: '1:976427213364:web:dc70221786da1608832061',
    messagingSenderId: '976427213364',
    projectId: 'instagram-practice-1b313',
    authDomain: 'instagram-practice-1b313.firebaseapp.com',
    storageBucket: 'instagram-practice-1b313.appspot.com',
    measurementId: 'G-6MY3L602PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiWbO-_KBAyFtLaNFCjfuwLS0UKakZ3HM',
    appId: '1:976427213364:android:ba7e01d7b9094943832061',
    messagingSenderId: '976427213364',
    projectId: 'instagram-practice-1b313',
    storageBucket: 'instagram-practice-1b313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYq6K-vvD9G7ZI-Ab8Ne7_J6TyXhFVzo',
    appId: '1:976427213364:ios:534494cb6fe329a2832061',
    messagingSenderId: '976427213364',
    projectId: 'instagram-practice-1b313',
    storageBucket: 'instagram-practice-1b313.appspot.com',
    iosBundleId: 'com.example.boonjae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYq6K-vvD9G7ZI-Ab8Ne7_J6TyXhFVzo',
    appId: '1:976427213364:ios:5cdce91e84b77c07832061',
    messagingSenderId: '976427213364',
    projectId: 'instagram-practice-1b313',
    storageBucket: 'instagram-practice-1b313.appspot.com',
    iosBundleId: 'com.example.boonjae.RunnerTests',
  );
}
